name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Log in to Docker Hub
      if: github.ref == 'refs/heads/main'  # Логинимся только при пуше в main
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKER_HUB_USERNAME }}
        password: ${{ secrets.DOCKER_HUB_TOKEN }}

    - name: Build the Docker image
      run: docker build . --file ./frontend/Dockerfile --tag iafansov/severstal:latest

    - name: Tag the Docker image with commit SHA
      run: docker tag iafansov/severstal:latest iafansov/severstal:${{ github.sha }}

    - name: Push Docker images to Docker Hub
      if: github.ref == 'refs/heads/main'  # Загружаем только при пуше в main
      run: |
        docker push iafansov/severstal:latest
        docker push iafansov/severstal:${{ github.sha }}
